Repository nvim-lualine/lualine.nvim, pull requests merged in 2021-05, with the labels that each got.

#206 Feat: Disable lualine on specific filetype
  README.md
  doc/lualine.txt
  lua/lualine/defaults.lua
  lua/lualine/init.lua
Labels: new feature

#209 Revert f08e8514 partially
  lua/lualine/init.lua
Labels: enhancement

#205 Performence improvments
  lua/lualine/highlight.lua
  lua/lualine/init.lua
  lua/lualine/utils/section.lua
Labels: enhancement

#127 testing
  .github/workflows/ci.yml
  .github/workflows/lint.yml
  Makefile
  tests/helpers.lua
  tests/minimal_init.lua
  tests/spec/component_spec.lua
  tests/spec/utils_spec.lua
Labels: enhancement

#213 Bugfix/perf improvements
  lua/lualine/highlight.lua
  lua/lualine/init.lua
  lua/lualine/utils/section.lua
Labels: bug

#237 Fix filename error message
  lua/lualine/components/filename.lua
Labels: bug

#234 enhancement: show diff when component is loaded
  lua/lualine/components/diff.lua
Labels: enhancement

#238 Allow x,y,z section to be themed independenly
  CONTRIBUTING.md
  lua/lualine/highlight.lua
Labels: enhancement
