Repository nvim-lualine/lualine.nvim, pull requests merged in 2021-02, with the labels that each got.

#62 Add molokai theme
  THEMES.md
  lua/lualine/themes/molokai.lua
Labels: new theme

#64 Adding wombat theme
  THEMES.md
  lua/lualine/themes/wombat.lua
Labels: new theme

#65 Adding material theme
  THEMES.md
  lua/lualine/themes/material.lua
Labels: new theme

#66 Add 16color theme
  THEMES.md
  lua/lualine/themes/16color.lua
Labels: new theme

#69 Add papercolor theme
  THEMES.md
  lua/lualine/themes/papercolor.lua
  lua/lualine/themes/papercolor_dark.lua
  lua/lualine/themes/papercolor_light.lua
Labels: new theme

#71 Add nightfly theme
  THEMES.md
  lua/lualine/themes/nightfly.lua
Labels: new theme

#81 Add codedark theme
  THEMES.md
  lua/lualine/themes/codedark.lua
Labels: new theme

#72 Adding gruvbox_metarial theme
  THEMES.md
  lua/lualine/themes/gruvbox_material.lua
Labels: new theme

#83 Don't show signify status symbols if the count < 1
  lua/lualine/components/signify.lua
Labels: enhancement

#79 Fix #33
  lua/lualine.lua
Labels: enhancement

#74 More themes
  THEMES.md
  lua/lualine/themes/ayu_dark.lua
  lua/lualine/themes/ayu_light.lua
  lua/lualine/themes/ayu_mirage.lua
  lua/lualine/themes/iceberg_dark.lua
  lua/lualine/themes/iceberg_light.lua
  lua/lualine/themes/jellybeans.lua
  lua/lualine/themes/oceanicnext.lua
  lua/lualine/themes/onehalf.lua
  lua/lualine/themes/seoul256.lua
  lua/lualine/themes/tomorrow.lua
Labels: new theme

#53 Added other sources for component configuration
  README.md
  doc/lualine.txt
  doc/tags
  lua/lualine.lua
Labels: new feature

#91 Fix lualine not appearing on :help
  doc/lualine.txt
  doc/tags
Labels: bug

#60 Adding component specific options
  README.md
  doc/lualine.txt
  doc/tags
  lua/lualine.lua
  lua/lualine/components/branch.lua
  lua/lualine/components/fileformat.lua
  lua/lualine/components/filename.lua
  lua/lualine/components/filetype.lua
  lua/lualine/highlight.lua
  lua/lualine/utils/component.lua
  lua/lualine/utils/cterm_colors.lua
  lua/lualine/utils/utils.lua
Labels: enhancement, new feature

#61 Add colors to signify
  README.md
  doc/lualine.txt
  doc/tags
  lua/lualine/components/signify.lua
  lua/lualine/utils/utils.lua
Labels: enhancement, new feature

#94 Powerline like section seperators v2
  README.md
  doc/lualine.txt
  lua/lualine.lua
  lua/lualine/components/signify.lua
  lua/lualine/highlight.lua
  lua/lualine/utils/component.lua
  lua/lualine/utils/utils.lua
Labels: new feature

#105 Enhancement: Stop creating unnececery hl groups
  lua/lualine.lua
  lua/lualine/highlight.lua
  lua/lualine/utils/utils.lua
Labels: enhancement

#95 feat: diagnostics api
  README.md
  lua/lualine/components/diagnostics.lua
Labels: new feature

#115 Refactor: removing cterm colors from themes
  CONTRIBUTING.md
  lua/lualine/highlight.lua
  lua/lualine/themes/16color.lua
  lua/lualine/themes/dracula.lua
  lua/lualine/themes/forest_night.lua
  lua/lualine/themes/gruvbox.lua
  lua/lualine/themes/gruvbox_material.lua
  lua/lualine/themes/molokai.lua
  lua/lualine/themes/nord.lua
  lua/lualine/themes/onedark.lua
  lua/lualine/themes/onelight.lua
  lua/lualine/themes/powerline.lua
  lua/lualine/themes/solarized_light.lua
  lua/lualine/themes/wombat.lua
Labels: enhancement

#87 Drop signify dependency
  README.md
  doc/lualine.txt
  lua/lualine/async.lua
  lua/lualine/components/diff.lua
  lua/lualine/components/signify.lua
Labels: enhancement

#119 (BugFix) filetype icon not updating with filechange
  lua/lualine/components/filetype.lua
Labels: bug
