Repository nvim-lualine/lualine.nvim, pull requests merged in 2021-03, with the labels that each got.

#116 Enable to set symbols for diff component
  README.md
  doc/lualine.txt
  lua/lualine/components/diff.lua
Labels: enhancement

#114 Feat: Add configuration in viml and through status function
  README.md
  doc/lualine.txt
  lua/lualine.lua
  lua/lualine/highlight.lua
Labels: enhancement, new feature

#92 Add tabline support
  README.md
  doc/lualine.txt
  doc/tags
  lua/lualine.lua
Labels: new feature

#131 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: enhancement

#130 refactor: removed ability to set theme in runtime
  lua/lualine.lua
Labels: enhancement

#132 refactor: moving to setup function
  README.md
  lua/lualine/config.lua
  lua/lualine/init.lua
Labels: enhancement

#136 Refactor: Highlight restoring after ColorScheme
  lua/lualine/components/diagnostics.lua
  lua/lualine/components/diff.lua
  lua/lualine/highlight.lua
  lua/lualine/init.lua
  lua/lualine/utils/utils.lua
Labels: enhancement

#133 refactor: completely move to setup function(remove warnings)
  lua/lualine/init.lua
Labels: enhancement

#151 feat: add diagnostic sources option vim_lsp
  README.md
  doc/lualine.txt
  lua/lualine/components/diagnostics.lua
Labels: enhancement, new feature

#155 Fix displaying relative paths.
  lua/lualine/components/filename.lua
Labels: bug
