Repository nvim-lualine/lualine.nvim, pull requests merged in 2021-04, with the labels that each got.

#159 Typo in docs: comparism -> comparison
  doc/lualine.txt
Labels: documentation

#165 fix: theme type check fix
  lua/lualine/init.lua
Labels: enhancement

#167 feat: addad chad&nnvim tree extensions
  README.md
  lua/lualine/extensions/chadtree.lua
  lua/lualine/extensions/nerdtree.lua
  lua/lualine/extensions/nvim-tree.lua
Labels: enhancement, new feature

#171 docs: updated lualine.txt
  README.md
  doc/lualine.txt
Labels: documentation

#172 Enhance: Adding issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: enhancement

#160 Miscellaneous changes
  CONTRIBUTING.md
  README.md
  doc/lualine.txt
  doc/tags
  lua/lualine/component.lua
  lua/lualine/components/special/eval_func_component.lua
  lua/lualine/highlight.lua
  lua/lualine/init.lua
Labels: enhancement

#174 Refactor: Remove cterm from hl_extractor
  lua/lualine/component.lua
  lua/lualine/components/diagnostics.lua
  lua/lualine/components/diff.lua
  lua/lualine/components/special/eval_func_component.lua
  lua/lualine/highlight.lua
  lua/lualine/init.lua
  lua/lualine/themes/auto.lua
  lua/lualine/utils/utils.lua
Labels: enhancement

#177 BugFix: fix vim functions displaying nil
  lua/lualine/components/special/eval_func_component.lua
Labels: bug

#178 Better fix to nil on vimfunc
  lua/lualine/components/special/eval_func_component.lua
Labels: enhancement

#168 Add modus_vivendi theme
  THEMES.md
  lua/lualine/themes/modus_vivendi.lua
Labels: new theme
