Repository nvim-lualine/lualine.nvim, pull requests merged in 2021-01, with the labels that each got.

#12 Added dracula theme
  README.md
  lua/lualine/themes/dracula.lua
Labels: enhancement

#8 Porting onedark theme
  README.md
  lua/lualine/themes/onedark.lua
Labels: enhancement

#7 Use table.concat instead of string concatentation
  lua/lualine.lua
  lua/lualine/highlight.lua
  lua/lualine/utils.lua
Labels: enhancement

#27 Added notermguicolor support and special effects
  CONTRIBUTING.md
  lua/lualine/highlight.lua
  lua/lualine/themes/dracula.lua
  lua/lualine/themes/forest_night.lua
  lua/lualine/themes/gruvbox.lua
  lua/lualine/themes/nord.lua
  lua/lualine/themes/onedark.lua
  lua/lualine/themes/powerline.lua
  lua/lualine/utils.lua
Labels: enhancement, new feature

#47 Handle undefined mode && fallback to normal mode highlighting
  lua/lualine/components/mode.lua
  lua/lualine/highlight.lua
Labels: bug

#48 Fix branch not changing
  lua/lualine/components/branch.lua
Labels: bug

#54 Bug fix Theme not rendered properly
  lua/lualine/highlight.lua
Labels: bug

#56 Added Completion Mode Label
  lua/lualine/components/mode.lua
Labels: enhancement

#59 Putting autocomands in a group
  lua/lualine.lua
Labels: enhancement

#58 Fixed signify component apearing on non repo buffer
  lua/lualine/components/signify.lua
Labels: bug

#57 Wider range of mode support
  lua/lualine/components/mode.lua
  lua/lualine/highlight.lua
Labels: enhancement

#73 run vimscript inside vim.api.nvim_exec
  lua/lualine.lua
Labels: enhancement

#68 Insted of calling git branch is read from HEAD
  lua/lualine/async.lua
  lua/lualine/components/branch.lua
Labels: enhancement

#63 Added solarized theme
  THEMES.md
  lua/lualine/themes/solarized.lua
  lua/lualine/themes/solarized_dark.lua
  lua/lualine/themes/solarized_light.lua
Labels: new theme
